"""07.09.2023-10:36:03

Revision ID: 0d7c30185a4f
Revises: 3367eca249ad
Create Date: 2023-09-07 10:36:11.012549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7c30185a4f'
down_revision: Union[str, None] = '3367eca249ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('image_tag', 'image_m2m_tag', ['image_id', 'tag_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('image_tag', 'image_m2m_tag', type_='unique')
    # ### end Alembic commands ###
