"""05.09.2023-22:45:49

Revision ID: 5bb4b99aaf74
Revises: dc8d941475e6
Create Date: 2023-09-05 22:45:56.218103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb4b99aaf74'
down_revision: Union[str, None] = 'dc8d941475e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'about',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'about',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
