"""06.09.2023-15:45:36

Revision ID: 6127c384b9cd
Revises: 26fc651d0e89
Create Date: 2023-09-06 15:45:45.293148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6127c384b9cd'
down_revision: Union[str, None] = '26fc651d0e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'cloud_public_id',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('images', 'cloud_version',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint('images_cloud_version_key', 'images', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('images_cloud_version_key', 'images', ['cloud_version'])
    op.alter_column('images', 'cloud_version',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('images', 'cloud_public_id',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###
