"""05.09.2023-20:40:22

Revision ID: 66c0e6214e4e
Revises: 77242bfc22cd
Create Date: 2023-09-05 20:40:29.119312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c0e6214e4e'
down_revision: Union[str, None] = '77242bfc22cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('small_image', sa.String(length=255), nullable=False))
    op.add_column('images', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('images', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'images', ['small_image'])
    op.alter_column('stars', 'level',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stars', 'level',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'images', type_='unique')
    op.drop_column('images', 'updated_at')
    op.drop_column('images', 'created_at')
    op.drop_column('images', 'small_image')
    # ### end Alembic commands ###
