"""06.09.2023-13:50:36

Revision ID: 87d21b1bf581
Revises: f3e944733a23
Create Date: 2023-09-06 13:50:43.932016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d21b1bf581'
down_revision: Union[str, None] = 'f3e944733a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('asset_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'asset_id')
    # ### end Alembic commands ###
