"""06.09.2023-13:47:39

Revision ID: d2c56e469505
Revises: 97e7ca33c69c
Create Date: 2023-09-06 13:47:46.409015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c56e469505'
down_revision: Union[str, None] = '97e7ca33c69c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('asset_id', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'asset_id')
    # ### end Alembic commands ###
