"""03.09.2023-23:51:46

Revision ID: d7ae209a04a5
Revises: 629f7926960c
Create Date: 2023-09-03 23:51:52.602800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7ae209a04a5'
down_revision: Union[str, None] = '629f7926960c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comments', sa.Column('emo_joy', sa.SmallInteger(), nullable=False))
    op.add_column('comments', sa.Column('emo_anger', sa.SmallInteger(), nullable=False))
    op.add_column('comments', sa.Column('emo_sadness', sa.SmallInteger(), nullable=False))
    op.add_column('comments', sa.Column('emo_surprise', sa.SmallInteger(), nullable=False))
    op.add_column('comments', sa.Column('emo_disgust', sa.SmallInteger(), nullable=False))
    op.add_column('comments', sa.Column('emo_fear', sa.SmallInteger(), nullable=False))
    op.add_column('images', sa.Column('image', sa.String(length=255), nullable=False))
    op.drop_constraint('images_image_url_key', 'images', type_='unique')
    op.create_unique_constraint(None, 'images', ['image'])
    op.drop_column('images', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'images', type_='unique')
    op.create_unique_constraint('images_image_url_key', 'images', ['image_url'])
    op.drop_column('images', 'image')
    op.drop_column('comments', 'emo_fear')
    op.drop_column('comments', 'emo_disgust')
    op.drop_column('comments', 'emo_surprise')
    op.drop_column('comments', 'emo_sadness')
    op.drop_column('comments', 'emo_anger')
    op.drop_column('comments', 'emo_joy')
    op.drop_table('stars')
    op.drop_table('logouts')
    # ### end Alembic commands ###
