"""04.09.2023-10:14:42

Revision ID: fe08a3317f11
Revises: 88351d1db599
Create Date: 2023-09-04 10:14:51.320448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe08a3317f11'
down_revision: Union[str, None] = '88351d1db599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('about', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'about')
    # ### end Alembic commands ###
